### ISSUE TITLE
I was able to install plugin but nothing comes after HTTP server listening at http://localhost:8080

### ISSUE THREAD

**Issue by gunjank** [danhigham/cf-live-stats#5]
I was able to install plugin but nothing comes after HTTP server listening at http://localhost:8080.
Steps - I using valid cf application name and trying to see live-stats. after using cf live-stats my-app-name it just stuck on HTTP server listening at http://localhost:8080

**Comment by damroo** [comment]
did you find a solution to it ?

**Comment by gunjank** [comment]
No, I didn't find any solution.

**Comment by jaimeambrosio** [comment]
Its problem of js of page :(

**Comment by gunjank** [comment]
I looked on browser (chrome) debug console and it seems failing due to NAN values where numbers expected from data.json call.
d3.min.js:1 Error: <text> attribute transform: Expected number, "translate(NaN,0)".
d3.min.js:1 Error: <path> attribute d: Expected number, "MNaN,298.78119558…".

**Comment by jaimeambrosio** [comment]
Yes. I hope the plugin developer solves it.

**Comment by danhigham** [comment]
Hey all, sorry about this. Just wrote a fix for it this morning, better late than never, right? 

See commit https://github.com/danhigham/cf-live-stats/commit/90f33d1268f1b9bf497699b3e0779a4c0fb8ccc6
